### ISSUE TITLE
Install script shows only html-code

### ISSUE THREAD

**Issue by rundekugel** [Froxlor/Froxlor-Installer#4]
If I execute
sudo apt-get install  default-mysql-server php php-mysql php-xml php-mbstring php-curl php-bcmath php-zip
and:
php froxlor-install.phar

I get only some HTML code
What's missing?

tried on xubuntu focal and Debian11 with php7.4

**Comment by rundekugel** [comment]
Problem was:
wget https://github.com/Froxlor/Froxlor-Installer/blob/master/bin/froxlor-install.phar
is downloading not the binary, but the code from git webpage
using 
git clone wget https://github.com/Froxlor/Froxlor-Installer/blob/master/bin/froxlor-install.phar
instead helped.

**Comment by d00p** [comment]
`git clone` is something totally different than `wget`ing a file...corrected in README
