### ISSUE TITLE
Install services error

### ISSUE THREAD

**Issue by rundekugel** [Froxlor/Froxlor-Installer#5]
Install script worked so far:
```
Froxlor is set up. Please open http://xxxxx/froxlor in your browser
To configure services, run 'php /var/w...
```
Executing showed this error:
...
php /var/www/froxlor/froxlor/install/scripts/config-services.php --froxlor-dir=/var/www/froxlor/froxlor/ --create
PHP Parse error:  syntax error, unexpected '1' (T_LNUMBER) in /var/www/froxlor/froxlor/install/scripts/config-services.php on line 31
...

**Comment by d00p** [comment]
Please Report this on Froxlor/Froxlor, as this file belongs there

**Comment by d00p** [comment]
fixed in https://github.com/Froxlor/Froxlor/commit/11533c2d7528586af4468ecade74f74a6368d36e
